### ISSUE TITLE
Abbreviated writing, tremolos, harmonics and 8va

### ISSUE THREAD

**Issue by allorens** [johentsch/ms3#10]
ms3 does not acknowledge abbreviated writing for repeated notes, tremolos, the real sound of harmonics or 8va lines, no matter if those come from a XML file or are engraved in MuseScore directly.

A passage such as this one:

![image](https://user-images.githubusercontent.com/61057980/96011027-beffd600-0e42-11eb-919f-556f1968253d.png)

would be processed as:

![image](https://user-images.githubusercontent.com/61057980/96011377-228a0380-0e43-11eb-810d-64b408551ad9.png)

**Comment by johentsch** [comment]
This is noteworthy and will have to be dealt with in a later version!

**Comment by johentsch** [comment]
This is possible now. The notelist now comes with a tremolo. The first note will have the value `1/4_r8_0`, the second one `1/4_r16_0` and the two halves will have `1/4_c16_1` and `1/4_c16_2` respectively, and have the same duration (1/2) and onset.
