### ISSUE TITLE
module 'webcolors' has no attribute 'CSS3_NAMES_TO_HEX'

### ISSUE THREAD

**Issue by kevinlinxc** [johentsch/ms3#115]
When I try to `import ms3`, I get this error:

```
    411 MS3_COLORS = list(MS3_HTML.values())
    412 CSS2MS3 = {c[4:]: c for c in MS3_COLORS}
--> 413 CSS_COLORS = list(webcolors.CSS3_NAMES_TO_HEX.keys())
    414 COLORS = sum([[c, CSS2MS3[c]] if c in CSS2MS3 else [c] for c in CSS_COLORS], [])
    415 rgba = namedtuple("RGBA", ["r", "g", "b", "a"])

AttributeError: module 'webcolors' has no attribute 'CSS3_NAMES_TO_HEX'
```

ms3 version 2.5.1
webcolors version 24.6.0

**Comment by kevinlinxc** [comment]
I changed the line to
`CSS_COLORS = list(webcolors._definitions._CSS3_NAMES_TO_HEX.keys())`

and it works now but maybe downgrading or pinning a version would be easier

**Comment by johentsch** [comment]
Thanks for reporting the fix, @kevinlinxc. I will fix this eventually.
