### ISSUE TITLE
Imported labels not showing on score

### ISSUE THREAD

**Issue by allorens** [johentsch/ms3#2]
When importing a set of annotations using the ``load_annotations`` and ``attach_labels`` methods, they are not shown on the score, although they are stored in the file as the expand function works afterwards. Would it be interesting to add an option whereby the user can choose whether to show them or not?

**Comment by johentsch** [comment]
The library never writes data without you asking for it to avoid data loss. ``s.store_mscx()`` should do the trick. Is this what you're looking for?

**Comment by allorens** [comment]
No. Imagine one has an older version of a file with all the annotations. Then you have a new XML for the same piece with different, updated editorial criteria and you want to import the annotations onto that new version. You import the XML in MuseScore and then the annotations. It'd be nice for them to be shown on the screen as if you had just annotated them.
