### ISSUE TITLE
Adding or converting to other formats

### ISSUE THREAD

**Issue by schef** [johentsch/ms3#45]
Hi guys,
in the past i converted musescore format to [lilypond](http://lilypond.org/) and to [synthv](https://dreamtonics.com/en/synthesizerv/). But I struggled with XML parsing.
Here are my repos:
- https://github.com/schef/musescore_to_synthv/blob/master/converter_example.py
- https://github.com/duhovniprojekt/duhovne_pjesme_novi_sad_1966/blob/master/scripts/ms2ly.py

You can here the result here https://www.youtube.com/watch?v=a3G_8BG2l7Q

Would this library help me skip the part where i have to convert the mscz/mscx to objects? Where should I start?
Would you be interested in adding something like that?
Thanks

**Comment by johentsch** [comment]
Hi @schef, so cool, if only I had seen three years ago that there were already MuseScore parsers around I could have been building on this :disappointed: 

> Would this library help me skip the part where i have to convert the mscz/mscx to objects?

Yes, what ms3 does is bringing the information from the score in a tabular format with timestamps. Whether it has all the information you would need for your conversion, I don't know but potentially yes. on https://github.com/DCMLab/dcml_corpora you'll find examples of the outputs in the folders `notes`, `measures` and `harmonies`. For conversion to Lilypond you would probably want all the markup (slurs, dynamics etc.) which we do not extract by default. You would get this markup by extracting `chords` (`ms3 extract -C`) which can be related to the notes they include via the `chord_id`. Does this help?

Including such a conversion would be beyond the scope of ms3 but I'd be happy to add an output format if it facilitates your tasks.

**Comment by schef** [comment]
What i really would want to have is a powerful musescore scripting tool. Because musescore at this point does not allow that (I would want to have python interpreter embedded in musescore as blender has) I thought that the best way to achieve this would be to manipulate the file because it is an open file format. The tasks i would need to do with this tool would be: extracting voices, add chords based on the harmony of the moment, extract lyrics, spellcheck the lyrics, create leadsheet (1. voice, chords and lyrics mostly for band musicians in the spirit of the realbook), extract the choir parts, etc. I'm working on restoration of an old Croatian/Yugoslavian church hymn book. It has over 380 choir songs with lyrics, without chords. The idea is to use the musescore as the source of information and then do some more beautiful engraving using lilypond.

So now, after having same experience parsing musescore file format what do you suggest it would be the best way to be able to manipulate the data in a nice python object way while preserving the information? (returning it to musescore file format) I looked at the code how you have it done until now. All your objects had the same fields but had None as a value if fields not used. Is this the way?
Thanks

**Comment by johentsch** [comment]
> I'm working on restoration of an old Croatian/Yugoslavian church hymn book. It has over 380 choir songs with lyrics, without chords. The idea is to use the musescore as the source of information and then do some more beautiful engraving using lilypond.

Sweet!

> The tasks i would need to do with this tool would be: extracting voices, add chords based on the harmony of the moment, extract lyrics, spellcheck the lyrics, create leadsheet (1. voice, chords and lyrics mostly for band musicians in the spirit of the realbook), extract the choir parts, etc. 

ms3 let's you extract voices (if you mean notes), lyrics and other markup, as DataFrames which are certainly among the most invaluable and versatile data structures to do whatever you want. It also lets you insert chord symbols into scores and write them back. The creation of leadsheets is not there yet but is something I had as an idea anyway (my idea was empty lead sheets with only chord symbols to display existing harmony datasets and enable their future enhancement with more transcription elements).

What would be your input for creating a lead sheet? In what format do you have the songs?
