### ISSUE TITLE
Multimeasure rests lead to wrong duration_qb [BUG]

### ISSUE THREAD

**Issue by m-k94** [johentsch/ms3#60]
**Describe the bug**

When using the shortcut "m", musescore displays multimeasure rests within a single bar, indicating the number of full bars without notes: 

![image](https://user-images.githubusercontent.com/75686579/235290191-c0ac0547-5c34-40aa-8a35-1b1f3985d085.png)

In mscx.measures(), this leads to some confusing outputs in the duration_qb column (also act_dur and quarterbeats as a consequence): In both parsed versions of the above score (with or without m activated), the number of rested measures is correct. However, in scores where multimeasure rest was activated, the duration of the _second_ full measure in the multirest is abnormally high. As if it were a single very long measure:

![mmr_bug](https://user-images.githubusercontent.com/75686579/235291903-6490d4e4-fb2b-4ab5-8e37-f4269dbec7a7.png)

The duration of multirest is superfluously added to a single bar. If someone were to sum the duration values, they could get drastically different piece durations depending on whether or not the m shortcut was used. The m shortcut should intuitively only affect how the music is displayed within musescore.

**ms3 version**
1.2.7 (first discovered in 1.2.3)

**To Reproduce**

I think any score with multimeasure rests should do. I can gladly send my example files if needed!

**Comment by johentsch** [comment]
Thanks for the report @m-k94, that's indeed something I've never dealt with. Will fix ASAP
