### ISSUE TITLE
What is the difference between old_tests and new_tests?

### ISSUE THREAD

**Issue by TGabor** [johentsch/ms3#66]
When reviewing the tests for https://github.com/openjournals/joss-reviews/issues/5195, I was wondering what the reason was to create a new_tests folder. Are the old_tests deprecated or still relevant?

**Comment by johentsch** [comment]
The old tests are deprecated.

**Comment by johentsch** [comment]
Cleaned up the unittests, old tests have been integrated again with v1.2.10
