### ISSUE TITLE
[JOSS] reference rendering

### ISSUE THREAD

**Issue by faroit** [johentsch/ms3#76]
👋 @johentsch here is a few more small issues about the references in the JOSS paper

1. the following paper (I guess ISMIR 23) should probably get a year even though it was just accepted. Otherwise try to change the rendering so that `inPress` isn't repeated twice.

<img width="715" alt="image" src="https://github.com/johentsch/ms3/assets/72940/0907e77b-044e-457e-83dc-67e1c177f2a3">

2. I guess the company is called `NPC Imaging`. So please change the capitalization here.

<img width="682" alt="image" src="https://github.com/johentsch/ms3/assets/72940/fd2872ee-d276-4332-85c2-9488bfa58ef2">

3. the colon in "bigger tent". should be outside of the hyphens.

<img width="698" alt="image" src="https://github.com/johentsch/ms3/assets/72940/a152a09e-73d6-4405-9a8c-34cfe8d8a49b">

this is part of the JOSS review https://github.com/openjournals/joss-reviews/issues/5195

**Comment by johentsch** [comment]
Thanks @faroit.

1. I had seen already and fixed together with your PR.
2. Done locally, they are `npc Imaging`, actually.
3. This is beyond my control, as I don't control where the period is rendered. It's not part of the [bibtex entry](https://github.com/johentsch/ms3/blob/joss_paper/paper/paper.bib#L220). What do you advise me to do?

**Comment by faroit** [comment]
Ok. Thanks. On 3. I would have to check if that's the norm. Maybe this is indeed correct then

**Comment by johentsch** [comment]
Seems more like glitch to me. As we could see from 1. the typesetting is not quite as accomplished as in LaTeX... I'll halt until your update on how to proceed.

**Comment by faroit** [comment]
@johentsch sorry for taking so long... I checked for 3 and it turns out that this is actually a US grammar rule and not a bug 😱

https://www.grammar-monster.com/lessons/quotation_(speech)_marks_punctuation_in_or_out.htm

So this can be closed.
